name: translate-auto

env:
  TRANS_TYPE: 'gpt'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APIKEY: ${{ secrets.APIKEY }}
  BASEURL: 'https://sapi.onechat.fun/v1'
  MODEL: 'gpt-3.5-turbo-0125'

on:
   schedule: # 定时任务
    - cron: "0 0,6,12,18 * * *" # 每天 0点，6点，12点，18点跑

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: 'zh'
        submodules: true
        fetch-depth: 0
    - name: Update upstream submodule
      continue-on-error: true
      run: |
           git config user.name "Automatic translator"
           git config user.email "<>"
           (cd data/ && git pull origin master --ff-only)
           git add data
           git commit -m "update to upstream"
           git push
  translate:
    needs: merge-upstream
    strategy:
      max-parallel: 9
      matrix:
        language: [ 'zh']
        files: ['data/[a-z]*/*.json']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: 'zh'
        submodules: true
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Set up dependencies
      run: |
           sudo apt-get install -y firefox
           pip3 install selenium webdriver_manager openai
    - name: Generate translations
      continue-on-error: true
      run: |
           cd $GITHUB_WORKSPACE
           mkdir data.${{ matrix.language }}  || true
           ./translation/translate.py --language ${{ matrix.language }} --maxrun 18000 --translate --$TRANS_TYPE ${{ matrix.files }}
           rm -Rf data.${{ matrix.language }} # Delete so we remove duplicates and regenerate in the next step
           ./translation/translate.py --language ${{ matrix.language }} --translate ${{ matrix.files }}
           (cd data && npm install)
           cd data.${{ matrix.language }}
           mkdir _generated || true
           [ -d _node ] || ln -s ../data/_node
           [ -f package.json ] || ln -s ../data/package.json
           npm run build
    - name: Save results
      continue-on-error: true
      run: |
           git config user.name "Automatic translator"
           git config user.email "<>"
           git add data.${{ matrix.language }}/ translation/cache/${{ matrix.language }}/
           git commit -m 'automatic translation'
           git status
           git checkout HEAD .
           git pull --rebase --autostash
           git push origin || sleep $((1 + $RANDOM % 100)) && git pull --rebase --autostash && git push origin || sleep $((1 + $RANDOM % 100)) && git pull --rebase --autostash && git push origin || sleep $((1 + $RANDOM % 100)) && git pull --rebase --autostash && git push origin
